export interface ILikes {
  id: number;
  str_userId: number;
}

export interface LikeData {
  addLike: ILikes;
}

export interface LikeVars {
  imgId?: number;
  sol?: number;
  imgSource?: string;
  img_id?: number;
}
// Generated by https://quicktype.io

export interface LikesResponse {
  data: Data;
}

export interface Data {
  addLike: AddLike;
}

export interface AddLike {
  id: number;
  str_userId: number;
}
