// Generated by https://quicktype.io

export interface User {
  id?: number;
  name?: string;
  username?: null;
  password?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  emailVerified?: null;
  language?: null;
  image?: null;
  token?: string;
}
