// Generated by https://quicktype.io

export interface NewsResponse {
  data: Data;
}

export interface Data {
  getNews: GetNew[];
}

export interface GetNew {
  id: null;
  title: string;
  content: string;
  link: string;
  pubDate: string;
}
